#!/bin/bash
if test "x$1" != "x"; then
    s3cmd sync -P --exclude=.*/\\..* "g/" "${1}g/"
else for r in `cat dist-targets`; do
       if test "x$r" != "x"; then
	   echo "Pushing to $r";
	   s3cmd sync -P --exclude=.*/\\..* "g/" "${r}g/"
       fi;
     done;
fi;
