all: markdown xmarkdown sizzle aloha

markdown:
	git clone git@github.com:beingmeta/markdown-js markdown
xmarkdown:
	git clone git@github.com:beingmeta/markdown-mark xmarkdown
sizzle:
	git clone git@github.com:beingmeta/sizzle sizzle
aloha:
	git clone git@github.com:beingmeta/Aloha-Editor aloha

update:
	cd markdown; git pull
	cd xmarkdown; git pull
