all: markdown xmarkdown sizzle aloha

pace:
	git clone git@github.com:beingmeta/pace pace
markdown:
	git clone git@github.com:beingmeta/markdown-js markdown
xmarkdown:
	git clone git@github.com:beingmeta/markdown-mark xmarkdown
sizzle:
	git clone git@github.com:beingmeta/sizzle sizzle
aloha:
	git clone git@github.com:beingmeta/Aloha-Editor aloha
iscroll:
	git clone https://github.com/beingmeta/iscroll.git iscroll
update:
	cd markdown; git pull
	cd xmarkdown; git pull
