update: flowtype brick normalize.css bootstrap
	cd flowtype; git pull
	cd brick; git pull
	cd normalize.css; git pull
	cd bootstrap; git pull

flowtype:
	git clone https://github.com/simplefocus/FlowType.JS.git flowtype

brick:
	git clone https://github.com/mozilla/brick.git

normalize.css:
	git clone https://github.com/necolas/normalize.css.git

bootstrap:
	git clone https://github.com/twbs/bootstrap.git

